repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        files: \.(c|h)$
        args: [--style=file]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        files: ".*\\.(?:c|h|html)$"
      - id: end-of-file-fixer
        files: ".*\\.(?:c|h|html)$"
